
[package]
name = "roo_parser"
description = "Roo is a Rust library that enables you to parse `.goo` files."
license = "MIT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"